#!/usr/bin/env bash
# Apple II WOZ/NIB reader: images that look like real captures (rotated
# tracks, sectors across the index point, 9/10-bit syncs, long gaps, address
# epilogue third byte != $EB), WOZ1, sparse track maps, FLUX tracks and
# damaged TRKS tables. Fixtures are generated by tools/a2_nibref.py.
#
# Optional: A2_REAL_WOZ_DIR=<dir> with user-supplied real captures
#   <name>.woz + <name>.expected.do  (expected sectors from an independent reader)
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
TOOL_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
RDEDISKTOOL="${RDEDISKTOOL:-$TOOL_ROOT/build/rdedisktool}"
NIBREF="$SCRIPT_DIR/tools/a2_nibref.py"
[[ -x "$RDEDISKTOOL" ]] || { echo "missing rdedisktool binary" >&2; exit 1; }

WORK="$(mktemp -d "${TMPDIR:-/tmp}/rde_a2_wozread.XXXXXX")"
trap '[[ -n "${KEEP_WORK:-}" ]] || rm -rf "$WORK"' EXIT

CHECKS=0
pass() { CHECKS=$((CHECKS + 1)); }
fail() { echo "FAIL: $*" >&2; exit 1; }
nibref() { python3 -I "$NIBREF" "$@"; }
same() { cmp -s "$1" "$2" || fail "$3: $1 differs from $2"; pass; }
mkblob() { head -c "$2" /dev/urandom >"$1"; }
# run a command, return its exit code; a crash (signal) is always a failure
rc_of() {
  set +e
  "$@" >"$WORK/out.log" 2>&1
  local rc=$?
  set -e
  [[ $rc -lt 128 ]] || { cat "$WORK/out.log" >&2; fail "crashed (rc=$rc): $*"; }
  echo "$rc"
}

# A DOS 3.3 disk with one file, built by rdedisktool on a .do image
mkblob "$WORK/blob.bin" 3000
"$RDEDISKTOOL" create "$WORK/dos.do" -f do --fs dos33 >/dev/null
"$RDEDISKTOOL" add "$WORK/dos.do" "$WORK/blob.bin" BLOB >/dev/null

# 1. Real-capture-like WOZ and rotated NIB
nibref make-woz reallike "$WORK/dos.do" "$WORK/reallike.woz"
nibref check-woz "$WORK/reallike.woz" "$WORK/dos.do" >/dev/null || fail "fixture self-check"
"$RDEDISKTOOL" convert "$WORK/reallike.woz" "$WORK/reallike.do" -f do >/dev/null || fail "convert reallike"
same "$WORK/dos.do" "$WORK/reallike.do" "reallike WOZ sectors"
"$RDEDISKTOOL" list "$WORK/reallike.woz" | grep -q "^BLOB " || fail "list reallike WOZ"; pass

nibref make-nib rotated "$WORK/dos.do" "$WORK/rotated.nib"
"$RDEDISKTOOL" convert "$WORK/rotated.nib" "$WORK/rotated.do" -f do >/dev/null || fail "convert rotated NIB"
same "$WORK/dos.do" "$WORK/rotated.do" "rotated NIB sectors"

# NB2 written by the independent tool
nibref make-nib nb2 "$WORK/dos.do" "$WORK/ref.nb2"
"$RDEDISKTOOL" convert "$WORK/ref.nb2" "$WORK/ref_nb2.do" -f do >/dev/null || fail "convert NB2"
same "$WORK/dos.do" "$WORK/ref_nb2.do" "NB2 sectors"

# Read rules (same as DOS 3.3 RWTS, checked against real DOS under sa2):
# a data or address epilogue other than DE AA makes only that sector unreadable;
# a missing fixed 1 bit in an address byte with unchanged values is accepted.
for kind in dataepi addrepi; do
  nibref make-nib "$kind" "$WORK/dos.do" "$WORK/$kind.nib"
  [[ $(rc_of "$RDEDISKTOOL" convert "$WORK/$kind.nib" "$WORK/$kind.do" -f do) == 2 ]] || fail "$kind: convert must exit 2"
  grep -q "T3/S0/H5:" "$WORK/out.log" && grep -q "^Warning: 1 sector(s) could not be copied" "$WORK/out.log" \
    || { cat "$WORK/out.log" >&2; fail "$kind: exactly T3 sector 5 unreadable"; }
  pass
  python3 -I -c 'import sys
a = open(sys.argv[1], "rb").read(); b = open(sys.argv[2], "rb").read()
bad = (3 * 16 + 5) * 256
sys.exit(0 if a[:bad] == b[:bad] and a[bad + 256:] == b[bad + 256:] else 1)' "$WORK/dos.do" "$WORK/$kind.do" \
    || fail "$kind: other sectors intact"
  pass
done
nibref make-nib fixedbit "$WORK/dos.do" "$WORK/fixedbit.nib"
[[ $(rc_of "$RDEDISKTOOL" convert "$WORK/fixedbit.nib" "$WORK/fixedbit.do" -f do) == 0 ]] || fail "fixedbit sector must read"
[[ $(grep -c "misses fixed bits" "$WORK/out.log") == 1 ]] && grep -q "Track 3, sector 5: address field misses fixed bits" "$WORK/out.log" \
  || { cat "$WORK/out.log" >&2; fail "fixedbit: exactly one warning for track 3 sector 5 (convert)"; }
pass
same "$WORK/dos.do" "$WORK/fixedbit.do" "fixedbit sectors"
[[ $(rc_of "$RDEDISKTOOL" info "$WORK/fixedbit.nib") == 0 ]] || fail "info fixedbit"
[[ $(grep -c "misses fixed bits" "$WORK/out.log") == 1 ]] || fail "fixedbit: exactly one warning (info)"; pass
nibref make-nib standard "$WORK/dos.do" "$WORK/clean.nib"
[[ $(rc_of "$RDEDISKTOOL" convert "$WORK/clean.nib" "$WORK/clean.do" -f do) == 0 ]] || fail "clean NIB"
! grep -q "misses fixed bits" "$WORK/out.log" || fail "clean NIB must not warn"; pass

# 2. WOZ1: read, then write one file and check that only rebuilt tracks change
nibref make-woz woz1 "$WORK/dos.do" "$WORK/w1.woz"
"$RDEDISKTOOL" info "$WORK/w1.woz" | grep -q "Format: Apple II WOZ v1" || fail "WOZ1 format"; pass
"$RDEDISKTOOL" convert "$WORK/w1.woz" "$WORK/w1.do" -f do >/dev/null || fail "convert WOZ1"
same "$WORK/dos.do" "$WORK/w1.do" "WOZ1 sectors"
cp "$WORK/dos.do" "$WORK/dos2.do"
mkblob "$WORK/blob2.bin" 1000
"$RDEDISKTOOL" add "$WORK/dos2.do" "$WORK/blob2.bin" BLOB2 >/dev/null
"$RDEDISKTOOL" add "$WORK/w1.woz" "$WORK/blob2.bin" BLOB2 >/dev/null || fail "add to WOZ1"
"$RDEDISKTOOL" convert "$WORK/w1.woz" "$WORK/w1b.do" -f do >/dev/null
same "$WORK/dos2.do" "$WORK/w1b.do" "WOZ1 after write"
nibref woz-info "$WORK/w1.woz" >"$WORK/w1info.txt"
grep -q "^version=1 info_version=1 crc_ok=1$" "$WORK/w1info.txt" || fail "WOZ1 stays WOZ1"; pass
grep -q "^trk0_bits=50034 splice=0x1234$" "$WORK/w1info.txt" || fail "untouched WOZ1 track keeps splice"; pass
python3 -I - "$WORK/w1.woz" <<'EOF' || fail "rebuilt WOZ1 track splice point"
import struct, sys
d = open(sys.argv[1], 'rb').read()
trks = d.index(b'TRKS') + 8
splices = [struct.unpack('<H', d[trks + i * 6656 + 6650:trks + i * 6656 + 6652])[0] for i in range(35)]
# DOS 3.3 writes the catalog/VTOC track 17: rebuilt -> 0xFFFF; others unchanged
sys.exit(0 if splices[17] == 0xFFFF and splices.count(0x1234) >= 30 else 1)
EOF
pass

# 3. Sparse WOZ: only the tracks ProDOS uses are present
"$RDEDISKTOOL" create "$WORK/pro.po" -f po --fs prodos -n SPARSE >/dev/null
"$RDEDISKTOOL" add "$WORK/pro.po" "$WORK/blob.bin" BLOB >/dev/null
"$RDEDISKTOOL" convert "$WORK/pro.po" "$WORK/pro.woz" -f woz >/dev/null
nibref sparse-woz "$WORK/pro.woz" "$WORK/sparse.woz" 0-1
[[ $(stat -c %s "$WORK/sparse.woz") -lt 143360 ]] || fail "sparse fixture is small"
"$RDEDISKTOOL" info "$WORK/sparse.woz" | grep -q "File System: ProDOS" || fail "sparse ProDOS detection"; pass
"$RDEDISKTOOL" extract "$WORK/sparse.woz" BLOB "$WORK/sparse_blob.bin" >/dev/null || fail "extract from sparse"
same "$WORK/blob.bin" "$WORK/sparse_blob.bin" "sparse WOZ file"
[[ $(rc_of "$RDEDISKTOOL" convert "$WORK/sparse.woz" "$WORK/sparse.do" -f do) == 2 ]] \
  || fail "convert with missing tracks must exit 2"
grep -q "528 sector(s) could not be copied" "$WORK/out.log" || fail "missing sectors reported"; pass

# Unformatted tracks only: info still works, filesystem Unknown
nibref sparse-woz "$WORK/pro.woz" "$WORK/track5.woz" 5
[[ $(rc_of "$RDEDISKTOOL" info "$WORK/track5.woz") == 0 ]] || fail "info on unformatted WOZ"
grep -q "File System: Unknown" "$WORK/out.log" || fail "unformatted WOZ is Unknown"; pass

# 4. FLUX track (WOZ 2.1): container info works, sector access refuses
nibref make-woz flux "$WORK/dos.do" "$WORK/flux.woz"
[[ $(rc_of "$RDEDISKTOOL" info "$WORK/flux.woz") == 0 ]] || fail "info on FLUX WOZ"
[[ $(rc_of "$RDEDISKTOOL" convert "$WORK/flux.woz" "$WORK/flux.do" -f do) == 2 ]] || fail "FLUX convert exit 2"
grep -q "FLUX" "$WORK/out.log" || fail "FLUX reason reported"; pass
cp "$WORK/flux.woz" "$WORK/flux_copy.woz"
[[ $(rc_of "$RDEDISKTOOL" add "$WORK/flux.woz" "$WORK/blob2.bin" BLOB2) != 0 ]] || fail "write to FLUX WOZ must fail"
same "$WORK/flux_copy.woz" "$WORK/flux.woz" "FLUX WOZ unchanged after refused write"

# 5. Damaged TRKS tables are rejected cleanly
for kind in bad-bitcount bad-block; do
  nibref make-woz "$kind" "$WORK/dos.do" "$WORK/$kind.woz"
  [[ $(rc_of "$RDEDISKTOOL" list "$WORK/$kind.woz") != 0 ]] || fail "$kind accepted"
  grep -q "points outside the file or is too short" "$WORK/out.log" || fail "$kind message"; pass
done
nibref make-woz bad-tmap "$WORK/dos.do" "$WORK/bad-tmap.woz"
[[ $(rc_of "$RDEDISKTOOL" convert "$WORK/bad-tmap.woz" "$WORK/bad-tmap.do" -f do) == 2 ]] || fail "bad TMAP index"
grep -q "16 sector(s) could not be copied" "$WORK/out.log" || fail "bad TMAP reports track 3"; pass

# 6. Optional real captures
if [[ -n "${A2_REAL_WOZ_DIR:-}" ]]; then
  n=0
  for w in "$A2_REAL_WOZ_DIR"/*.woz; do
    exp="${w%.woz}.expected.do"
    [[ -f "$exp" ]] || continue
    "$RDEDISKTOOL" convert "$w" "$WORK/real.do" -f do >/dev/null 2>&1 || true
    python3 -I - "$exp" "$WORK/real.do" <<'EOF' || fail "real capture $w"
import sys
a, b = open(sys.argv[1], 'rb').read(), open(sys.argv[2], 'rb').read()
# sectors the independent reader could not read are all-zero in the expectation
bad = [i for i in range(560) if any(a[i*256:i*256+256]) and a[i*256:i*256+256] != b[i*256:i*256+256]]
print(f'  real {sys.argv[1]}: {560 - len(bad)}/560 sectors match')
sys.exit(1 if bad else 0)
EOF
    pass; n=$((n + 1))
  done
  echo "  real captures judged: $n"
else
  echo "  SKIP real captures (A2_REAL_WOZ_DIR not set; not judged)"
fi

echo "PASS test_apple_woz_read ($CHECKS checks)"
